### ISSUE TITLE
JNativeHook error message when starting two instances of AsTeRICS

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS#103]
When starting two instances of AsTeRICS the jnativehook service bundle cannot be activated and an error message is thrown.

The debug console shows the following root exception:

Caused by: java.lang.RuntimeException: C:\Users\mad\AppData\Local\Temp\JNativeHook-1.2.RC2.dll (Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird)
        at org.jnativehook.GlobalScreen.loadNativeLibrary(GlobalScreen.java:609)
        at org.jnativehook.GlobalScreen.<init>(GlobalScreen.java:86)
        at org.jnativehook.GlobalScreen.<clinit>(GlobalScreen.java:67)
        ... 28 more
Caused by: java.io.FileNotFoundException: C:\Users\mad\AppData\Local\Temp\JNativeHook-1.2.RC2.dll (Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at org.jnativehook.GlobalScreen.loadNativeLibrary(GlobalScreen.java:570)
        ... 30 more

Obviously the native dll file is busy and cannot be accessed two times.

Possible solutions:
upgrade to newer version of jnativehook, maybe it's already fixed?

workaround:
Manually delete .dll file after startup of bundle.

**Comment by deinhofer** [comment]
Seems to be fixed already:
https://github.com/kwhat/jnativehook/issues/75

**Comment by deinhofer** [comment]
now tested for Linux (Ubuntu 12 LTS), and Mac OSX: 
* works fine
* no strange error messages more
* but blocking of keys not working
* temp file is correctly deleted after exit of application
