### ISSUE TITLE
CrossHair/Tooltip Plugin won't start: "TRANSLUCENT translucency is not supported"

### ISSUE THREAD

**Issue by benjaminaigner** [asterics/AsTeRICS#318]
If I try to start a model with the crosshair plugin, it won't start.
Error message:
![Screenshot from 2019-05-09 14-48-16](https://user-images.githubusercontent.com/6196086/57460382-4d971d80-7275-11e9-82bc-8ef3465792af.png)

System:
Debian Stretch (stable), x86-64
Cinnamon Desktop (lightdm)
AsTeRICS 4.0.0-alpha1

**Comment by klues** [comment]
Thanks for filing the bug. Could you please also post the stacktrace so that I can see where the exception is thrown?

**Comment by benjaminaigner** [comment]
Sry for missing your request.

AsTeRICS Version: 4.1.0
Here are both stacktraces, for the Crosshair and the Tooltip Plugin:

```
2020-06-02 09:40:32.750 SEVERE [DeploymentManager runModel] java.lang.UnsupportedOperationException: TRANSLUCENT translucency is not supported.
        at java.awt.Window.setOpacity(Window.java:3627)
        at java.awt.Frame.setOpacity(Frame.java:962)
        at eu.asterics.component.actuator.tooltip.GUI.<init>(GUI.java:73)
        at eu.asterics.component.actuator.tooltip.TooltipInstance.start(TooltipInstance.java:321)
        at eu.asterics.mw.are.DeploymentManager.runModel(DeploymentManager.java:582)
        at eu.asterics.mw.services.AREServices.runModelInternal(AREServices.java:440)
        at eu.asterics.mw.services.AREServices$7.call(AREServices.java:409)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

```
2020-06-02 09:40:32.740 SEVERE [DeploymentManager runModel] java.lang.UnsupportedOperationException: TRANSLUCENT translucency is not supported.
        at java.awt.Window.setOpacity(Window.java:3627)
        at eu.asterics.component.actuator.crosshaircursorcontrol.GUI.<init>(GUI.java:90)
        at eu.asterics.component.actuator.crosshaircursorcontrol.CrosshairCursorControlInstance.start(CrosshairCursorControlInstance.java:562)
        at eu.asterics.mw.are.DeploymentManager.runModel(DeploymentManager.java:582)
        at eu.asterics.mw.services.AREServices.runModelInternal(AREServices.java:440)
        at eu.asterics.mw.services.AREServices$7.call(AREServices.java:409)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by klues** [comment]
branch `klaus/issue#318/translucency-not-supported` should fix it, please verify.
Afterwards we can merge #344

**Comment by benjaminaigner** [comment]
THX!
